### ISSUE TITLE
production aggregation 

### ISSUE THREAD

**Issue by dmcglinn** [mcglinnlab/soil_turnover#1]
Hey @stranda, when you have a chance can you please take a look at the following script https://github.com/mcglinnlab/soil_turnover/blob/master/scripts/data_merge.R . My key question is to make sure I'm aggregating over the frames to the tube scale correctly. Seth mentioned that simply taking the mean as you suggested may not be appropriate. Here is the head of the unaggregated data:

```
  tube session     fuid frame   fulldate julian1990 ring block co2treat ntreat new_session interval
1    1       1  1-1-1-1     1 1998-10-21      10520    1     1  AMBIENT      0          NA      186
2    1       1 1-1-11-1    11 1998-10-21      10520    1     1  AMBIENT      0          NA      186
3    1       1 1-1-13-1    13 1998-10-21      10520    1     1  AMBIENT      0          NA      186
4    1       1 1-1-15-1    15 1998-10-21      10520    1     1  AMBIENT      0          NA      186
5    1       1 1-1-17-1    17 1998-10-21      10520    1     1  AMBIENT      0          NA      186
6    1       1 1-1-19-1    19 1998-10-21      10520    1     1  AMBIENT      0          NA      186
  root.len.prod root.len.mort root.len.stand rhiz.len.prod rhiz.len.mort rhiz.len.stand myc.prod myc.mort
1             0             0              0       0.00000             0        0.00000        0        0
2             0             0              0       0.00000             0        0.00000        0        0
3             0             0              0      51.39552             0       51.39552        0        0
4             0             0              0       0.00000             0        0.00000        0        0
5             0             0              0       0.00000             0        0.00000        0        0
6             0             0              0       0.00000             0        0.00000        0        0
  myc.stand tube.x tube.y
1         0     NA     NA
2         0     NA     NA
3         0     NA     NA
4         0     NA     NA
5         0     NA     NA
6         0     NA     NA
```

and here is the output from the aggregated productivity

```
  tube session ring block   fulldate root.len.prod root.len.mort root.len.stand rhiz.len.prod rhiz.len.mort
1    1       1    1     1 1998-10-21     0.9900087             0      0.9900087     3.0232661             0
2    2       1    1     1 1998-10-21     0.7972318             0      0.7972318     0.9171742             0
3    3       1    1     1 1998-10-21     1.6859079             0      1.6859079     0.0000000             0
4    4       1    1     1 1998-10-21     7.4809974             0      7.4809974     0.0000000             0
5    5       1    1     1 1998-10-21     6.6240592             0      6.6240592     4.4403928             0
6    6       1    1     1 1998-10-21     0.0000000             0      0.0000000     0.0000000             0
  rhiz.len.stand myc.prod myc.mort myc.stand    tube.x    tube.y
1      3.0232661    0.000        0     0.000       NaN       NaN
2      0.9171742    0.000        0     0.000       NaN       NaN
3      0.0000000    0.000        0     0.000 12.800120  2.795690
4      0.0000000    0.000        0     0.000       NaN       NaN
5      4.4403928 1697.159        0  1697.159  2.335264 -6.640303
6      0.0000000    0.000        0     0.000       NaN       NaN
```

**Comment by stranda** [comment]
The main problem with using the mean in my mind is getting the denominator specified correctly (in other words, how many frames with zeros do you want to include)  In the dataframes available to you, I have eliminated dead frames and tubes (which I believe should not go into a mean estimate) but I have included frames that have no production.  I suspect that's what Seth is talking about

**Comment by pritchards** [comment]
thanks, Allan.  That is indeed the issue i was referring to.

**Comment by dmcglinn** [comment]
Thanks guys, ok so averaging across the frames is acceptable in this
context because the frames without roots have already been removed right?

On Wed, May 13, 2015 at 11:22 AM, pritchards notifications@github.com
wrote:

> thanks, Allan. That is indeed the issue i was referring to.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mcglinnlab/soil_turnover/issues/1#issuecomment-101713876
> .

## 

Daniel J. McGlinn, PhD
Assistant Professor
College of Charleston
Department of Biology
Harbor Walk West, rm 203
360 Concord Street
Charleston, SC 29401
http://mcglinn.web.unc.edu/
office: 843-953-0190
cell: 405-612-1780

**Comment by pritchards** [comment]
nope.  if there are no roots in a given frame during the experiment then data do not exist for those (not even zeros).

**Comment by pritchards** [comment]
unless Allan has created a file with zeros for frames with no roots....

**Comment by stranda** [comment]
Which is what I did.
